model = "gpt-5.2-codex"
model_reasoning_effort = "high"
[projects."/Users/demfabris/Documents/Development/xt"]
trust_level = "trusted"

[projects."/Users/demfabris/Documents/Development/Clairvo/backend"]
trust_level = "trusted"

[projects."/Users/demfabris/Documents/Development/Clairvo/frontend"]
trust_level = "trusted"

[projects."/Users/demfabris"]
trust_level = "trusted"

[projects."/Users/demfabris/Documents/Development/psicopilot"]
trust_level = "trusted"

[projects."/Users/demfabris/Documents/Development/xterm-expr"]
trust_level = "trusted"

[notice.model_migrations]
"gpt-5.1-codex-max" = "gpt-5.2-codex"
